module: SwiftKueryPostgreSQL
author: IBM & Kitura project authors
github_url: https://github.com/Kitura/Swift-Kuery-PostgreSQL/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false
